version: '3'
services:
  app:
    build: .
    container_name: php_app
    volumes:
      - ./:/var/www/html/
    depends_on:
      - db
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=todo_user
      - MYSQL_PASSWORD=password
      - MYSQL_DB=todolist
  db:
    image: mariadb:latest
    container_name: mariadb_db
    environment:
      - MYSQL_ROOT_PASSWORD=mysqlrootpass
      - MYSQL_DATABASE=todolist
      - MYSQL_USER=todo_user
      - MYSQL_PASSWORD=password
    volumes:
      - dbdata:/var/lib/mysql
  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
volumes:
  dbdata:
